#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
source ./env_autodl.sh
ensure_gpu_env

cd "$WENET_ROOT/examples/aishell/s0"

MODEL_NAME="${MODEL_NAME:-aishell_u2pp_conformer}"
OUT_DIR="$RUNTIME_MODEL_ROOT/$MODEL_NAME"
mkdir -p "$OUT_DIR"

echo "== Package runtime model =="
echo "EXP_DIR=$EXP_DIR"
echo "OUT_DIR=$OUT_DIR"

FINAL_ZIP="$(find "$EXP_DIR" -type f -name 'final.zip' | sort | tail -n 1 || true)"
if [ -z "$FINAL_ZIP" ]; then
  echo "final.zip not found in $EXP_DIR. Run scripts/05_export_model.sh first." >&2
  exit 1
fi

cp "$FINAL_ZIP" "$OUT_DIR/final.zip"

if [ -f data/dict/lang_char.txt ]; then
  cp data/dict/lang_char.txt "$OUT_DIR/units.txt"
elif [ -f data/lang_char.txt ]; then
  cp data/lang_char.txt "$OUT_DIR/units.txt"
else
  echo "Cannot find units file. Search data/ manually." >&2
  find data -maxdepth 3 -type f | sort | head -50
  exit 1
fi

cat > "$OUT_DIR/README_runtime.txt" <<EOF
Runtime model package generated by wenet_aishell_autodl_project.

Files:
- final.zip: exported WeNet model
- units.txt: unit dictionary

Source:
$WENET_ROOT/examples/aishell/s0/$EXP_DIR

Start docker websocket server:
cd $PROJECT_ROOT
MODEL_DIR=$OUT_DIR bash scripts/07_start_runtime_docker.sh
EOF

tar -czf "$RUNTIME_MODEL_ROOT/${MODEL_NAME}.tar.gz" -C "$RUNTIME_MODEL_ROOT" "$MODEL_NAME"
ls -lh "$OUT_DIR" "$RUNTIME_MODEL_ROOT/${MODEL_NAME}.tar.gz"